[package]
name = "rikky_modoki-aux2"
version = "0.0.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]
name = "rikky_modoki_aux2"

[dependencies]
anyhow = "1.0.104"
aviutl2 = "0.46.1"
dirs = "7.0.0"
encoding_rs = "0.8.41"
lazy-regex = "3.6.1"
native-dialog = "0.9.7"
sweeplsd = { path = "external/sweeplsd" }
tracing = "0.1.44"
