[package]
name = "rikky_modoki-aux2"
version = "0.6.1"
edition = "2024"

[lib]
crate-type = ["cdylib"]
name = "rikky_modoki_aux2"

[dependencies]
anyhow = "1.0.104"
aviutl2 = "0.47.0"
dirs = "7.0.0"
encoding_rs = "0.8.41"
lazy-regex = "3.6.1"
native-dialog = "0.9.7"
process_path = "0.1.4"
rustfft = "6.4.1"
sweeplsd = { path = "external/sweeplsd" }
tracing = "0.1.44"
windows = { version = "0.62.2", features = ["Win32_Graphics_Gdi", "Win32_Graphics_GdiPlus", "Win32_System_LibraryLoader", "Win32_UI_Controls", "Win32_UI_HiDpi", "Win32_UI_Input_KeyboardAndMouse", "Win32_UI_WindowsAndMessaging"] }
xxhash-rust = { version = "0.8.18", features = ["xxh3"] }
